### ISSUE TITLE
can't load pre trained models for inference

### ISSUE THREAD

**Issue by Valitag** [ibrahimethemhamamci/CT-CLIP#23]
Hi,
I try to load the pre-trained models for inference: 
CT_CLIP_zeroshot.pt,
CT_LiPro.pt

I run:
run_zero_shot.py with these parameters:
clip.load(r"C:\Users\pretrained_models\CT_CLIP_zeroshot.pt")

inference = CTClipInference(
    clip,
    data_folder = r'\dataset\valid',
    reports_file= r"C:\labels_reports\dataset_radiology_text_reports_validation_reports.csv",
    labels = r"C:\labels_reports\valid_labels.csv",
    batch_size = 1,
    results_folder="/dataset/results/",
    num_train_steps = 1,
)

errors:
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'CXRBertTokenizer'. 
The class this function is called from is 'BertTokenizer'.
You are using a model of type cxr-bert to instantiate a model of type bert. This is not supported for all configurations of models and can yield errors.
Some weights of BertModel were not initialized from the model checkpoint at microsoft/BiomedVLP-CXR-BERT-specialized and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

self.load_state_dict(pt)
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CTCLIP:
	Unexpected key(s) in state_dict: "text_transformer.embeddings.position_ids". 

also when I run ct_lipro_inference.py:
I got an error when loading the model

**Comment by Raingate** [comment]
Hi! I met almost same problem. when I load pretrained model CT_CLIP_zeroshot.pt, I got following errors:

Traceback (most recent call last):
  File "zeroshot_ground.py", line 45, in <module>
    clip.load("/ailab/user/fengjinghao/CRAFT/Med_Grounding/baselines/CT-CLIP/ckpt/CT_CLIP_zeroshot.pt")
  File "/ailab/user/fengjinghao/CRAFT/Med_Grounding/baselines/CT-CLIP/CT_CLIP/ct_clip/ct_clip.py", line 593, in load
    self.load_state_dict(pt)
  File "/ailab/user/fengjinghao/CRAFT/Med_Grounding/baselines/CT-CLIP/CT_CLIP/ct_clip/ct_clip.py", line 587, in load_state_dict
    return super().load_state_dict(*args, **kwargs)
  File "/ailab/user/fengjinghao/.conda/envs/cxr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CTCLIP:
        **Missing key(s) in state_dict: "visual_transformer.vq._codebook.embed_avg". 
        Unexpected key(s) in state_dict: "text_transformer.embeddings.position_ids".** 
        
looks like a mismatch indeed!

**Comment by liu3xing3long** [comment]
follow transformer versions in transformer_maskgit (eg. transformers==4.30.1) makes it work.

**Comment by liu3xing3long** [comment]
> follow transformer versions in transformer_maskgit (eg. transformers==4.30.1) makes it work.

only solve this issue 'nexpected key(s) in state_dict: "text_transformer.embeddings.position_ids".'

**Comment by liu3xing3long** [comment]
Missing key(s) in state_dict: "visual_transformer.vq._codebook.embed_avg". is caused by vector quantinization package -> using vector-quantize-pytorch==1.1.2 will fix it
